version: "3"
services:
  app:
    container_name: productivity-trakcer-app
    build: .
    ports:
      - "4011:4011"
    restart: on-failure
    volumes:
      - app:/user/src/app/
    networks:
      - productivity-trakcer-network
    depends_on:
      - db
  
  db:
    container_name: productivity-trakcer-db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=devpostgres
      - POSTGRES_PASSWORD=devpostgres
      - POSTGRES_DB=gorm
      - POSTGRES_HOST=db
    ports:
      - "5433:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - productivity-trakcer-network

volumes:
  app:
  db_postgres:

networks: 
  productivity-trakcer-network:
    driver: bridge