[App]
name = "Productivity Tracker API"
env = "local"
port = 4011

[Database]
driver = "postgres"
dburl = "postgres://devpostgres:devpostgres@localhost:5432/gorm"
# dburl = "postgres://devpostgres:devpostgres@productivity-trakcer-db:5432/gorm"

# [Logger]
# driver = "mongodb"
# host = "localhost"
# port = 27017
# password = "test saja"
# Dbnumber = 2