name: Build Productivity-Trakcer-API App
on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod download

      - name: Verify module
        run: go mod verify

      - name: Go testing
        run: |
          cd business
          go test -v ./...

      - name: Build go App
        run: go build -v ./...

      - name: Check go vet linting
        run: go vet ./...
